version: '3'
services:
  app:
    container_name: whiskers
    restart: always 
    build: . 
    ports: 
      - "8080:8080"
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db